// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYR4oFBJjboLor9bo1gPr5La3KTX5MC0I',
    appId: '1:10410346190:web:24e814cb81c3046ffe329f',
    messagingSenderId: '10410346190',
    projectId: 'newsmoderator-fe1a9',
    authDomain: 'newsmoderator-fe1a9.firebaseapp.com',
    storageBucket: 'newsmoderator-fe1a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeGUkQhPJPpd1xkJPVksOAWhQP4_KAA1s',
    appId: '1:10410346190:android:693e23cb54ff65c5fe329f',
    messagingSenderId: '10410346190',
    projectId: 'newsmoderator-fe1a9',
    storageBucket: 'newsmoderator-fe1a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBePSArBsiYr2Mh-oxSQeF5ylsNj5QPLRc',
    appId: '1:10410346190:ios:fac3203fbbbece2afe329f',
    messagingSenderId: '10410346190',
    projectId: 'newsmoderator-fe1a9',
    storageBucket: 'newsmoderator-fe1a9.appspot.com',
    iosBundleId: 'com.example.newsapp',
  );
}
